### PR TITLE
ci: Sync github actions

### PR DESCRIPTION
**Pull request by BeyondRobot**

### CODE REVIEW

**Comment by JinnyYi** [comment]
The download supports fragmented downloads via the standard HTTP header `Range`, ref: https://developer.qiniu.com/kodo/1232/download-process. But when I setting `Range` request header(file size is 3997010, and `Range: bytes=1676591-1731475`), I got the response:

```html
<html>
  <head><title>416 Requested Range Not Satisfiable</title></head>
  <body bgcolor="white">
    <center><h1>416 Requested Range Not Satisfiable</h1></center>
    <hr><center>openresty/1.13.6.1</center>
  </body>
</html>
```

And the response header include: 
```
Content-Range: bytes */1124
```


<blockquote><div><strong><a href="https://developer.qiniu.com/kodo/1232/download-process">下载资源_使用指南_对象存储 - 七牛开发者中心</a></strong></div><div>下载资源</div></blockquote>

**Comment by JinnyYi** [comment]
The reason for the error `416 Requested Range Not Satisfiable` is that the domain name used for the test has expired. And there is no interface to check the validity of the test domain name at the moment.

The reason for the error tested on teamcity is that reading with offset and size will get HTTP 206 partial content status code.

**Comment by Xuanwo** [comment]
Can you start an issue for this problem? I will check the qiniu test account later.

**Comment by JinnyYi** [comment]
> Can you start an issue for this problem? I will check the qiniu test account later.

The test account on teamcity is active. My local test domain expired. I've fixed the test cases.

**Pull request closed without merging**
